config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  Rails.application.routes.draw do
    root 'home#index'

    get '/login',     to: 'sessions#new',     as: 'login'
    get '/logout',    to: 'sessions#destroy', as: 'logout'
    post '/sessions', to: 'sessions#create',  as: 'sessions'

    get '/stir/:device_id', to: 'stir#stir', as: 'stir'
    get '/poll/:device_id', to: 'stir#poll', as: 'poll'

    namespace 'admin' do
      get '/lookup', to: 'devices#lookup', as: 'lookup'
      resources :users
    end
  end
end

app/models/device.rb
class Device < ApplicationRecord

  belongs_to :user

  enum icon: [ :generic, :desktop, :laptop, :server, :printer ]

  scope :active, ->() { where(:active => true) }

  validates :name, presence: true
  validates :user, presence: true
  validates :active, inclusion: { in: [true, false] }
  validates :icon, presence: true, inclusion: { in: icons.keys }
  validates :host, presence: { message: "can't be blank if the device is active." }, if: :active
  validate  :host, :validate_host, if: :active
  validates :mac, presence: { message: "can't be blank if the device is active." }, if: :active
  validate  :mac, :validate_mac, if: :active

  after_initialize :set_defaults, if: :new_record?

  def set_defaults
    self.icon ||= :generic
  end

  def validate_host
    return if errors.include?(:host) ||
              DeviceTools.valid_ip?(self.host) ||
              DeviceTools.valid_hostname?(self.host)
    errors.add(:host, "is an invalid IP address or hostname")
  end

  def validate_mac
    return if errors.include?(:mac) ||
              DeviceTools.valid_mac?(self.mac)
    errors.add(:mac, "is an invalid MAC address")
  end

  def stir
    DeviceTools.stir(self.mac)
  end

  def poll
    DeviceTools.poll([self])
  end

  def mac=(new_mac)
    super(new_mac.downcase)
  end

  def mac
    super&.downcase
  end
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @user = User.find(params[:user_id])
    @device = @user.devices.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @user = User.find(params[:user_id])
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /devices/lookup/:input
  def lookup
    term = params[:term]
    hosts = Mapping.known_hosts(freshen: true)
    # found_devices = DeviceTools.lookup(lookup_params[:term].to_s.strip)

    respond_to do |format|
      format.json { render json: {results: hosts}, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
      @user = @device.user
    end

    # Only allow a list of trusted parameters through.
    def device_params
      params.require(:device).permit(:name, :host, :mac, :active, :icon, :state, :user_id)
    end

    def lookup_params
      params.permit(:term, :q, :_type)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper

    ##
    # View helpers
    ##

    def device_icons
        {
            :generic => 'plug',
            :desktop => 'desktop',
            :laptop => 'laptop',
            :server => 'server',
            :printer => 'print'
        }
    end

    def device_icon(icon, options={})
        return fa_icon(device_icons[icon.to_sym], options)
    end

    def device_status(device)
        if device.active == false
            "DISABLED"
        else
            "POLLING"
        end
    end
    
end

app/views/admin/devices/_form.html.slim
= form_with(model: [:admin, @user, device], local: true) do |form|
  - if device.errors.any?
    #error_explanation
      h2 #{pluralize(device.errors.count, "error")} prohibited this device from being saved:

      ul
        = device.errors.full_messages.each do |message|
          li= message

  .field.row
    = form.label :name
    = form.text_field :name

  .field.row
    = form.label :host
    = form.text_field :host

  .field.row
    = form.label :mac
    = form.text_field :mac,
        { maxlength: 17,
        pattern: "([0-9a-fA-F][0-9a-fA-F]:){5}([0-9a-fA-F][0-9a-fA-F])" }


  .field.row
    = form.label :active
    = form.check_box :active

  .field.row
    = form.label :icon
    .radiobar
      - device_icons.each do |sym, str|
        = form.radio_button :icon, sym.to_s, {style: 'display: none'}
        = form.label :icon, device_icon(sym), {value: sym.to_s}

    = form.hidden_field :user_id

  .actions
    = link_to fa_icon('arrow-left', text: 'Back'), '', {class: 'button'}
    = form.button :submit, {class: 'button'} do
      = fa_icon('save', text: 'Save')

app/views/admin/devices/detail.html.slim
h1 New Device

= render 'form', device: @device

= link_to 'Back', admin_users_path