config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  Rails.application.routes.draw do
    root 'home#index'

    get '/login',     to: 'sessions#new',     as: 'login'
    get '/logout',    to: 'sessions#destroy', as: 'logout'
    post '/sessions', to: 'sessions#create',  as: 'sessions'

    get '/stir/:device_id', to: 'stir#stir', as: 'stir'
    get '/poll/:device_id', to: 'stir#poll', as: 'poll'

    namespace 'admin' do
      get '/lookup', to: 'devices#lookup', as: 'lookup'
      resources :users
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :devices, inverse_of: :user, :dependent => :destroy
  accepts_nested_attributes_for :devices,
    allow_destroy: true,
    reject_if: :all_blank

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :admin, inclusion: { in: [true, false] }

  after_initialize :set_defaults, if: :new_record?

  def set_defaults
    self.admin ||= false
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :ensure_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @admins = User.where(admin: true).order(name: :asc).includes(:devices)
    @users = User.where(admin: false).order(name: :asc).includes(:devices)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to :action => :edit
  end

  # GET /users/new
  def new
    @user = User.new
    @hosts = Mapping.known_hosts
  end

  # GET /users/1/edit
  def edit
    @hosts = Mapping.known_hosts
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        @hosts = Mapping.known_hosts
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        @hosts = Mapping.known_hosts
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def ensure_admin
      redirect_to root_path unless current_user&.admin
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "User does not exist."
      redirect_to admin_users_path
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :email, :name, :admin, :password, :password_confirmation,
        devices_attributes: [
          :id, :name, :icon, :host, :mac, :active, :_destroy
        ]
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_card_user.html.slim
.user.card{id: user.id}
    = link_to(edit_admin_user_path(user), {class: 'section'}) do
        aside
            = fa_icon(user.admin ? "id-card" : "user")
        main
            h3.title.name= user.name
            h4.subtitle.email
                - username, domain = user.email.split('@')
                span.username= username
                span.domain= '@' + domain

    = render partial: 'device_button', collection: user.devices, as: :device
/        = link_to fa_icon("plus", text: "Add a device"), new_admin_user_device_path(user.id), {class: 'button'}

app/views/admin/users/_device_button.html.slim
  = link_to stir_path(device), { :class => [device.active ? 'device' : 'device inactive'], :id => "device_#{device.id}", data: {id: device.id} } do
    .left-side
      .icon= device_icon(device.icon)
    .progress[data-width="0"]
    .middle
      .name= device.name
    .right-side
      .status
        .text-container
          .text Waiting...
        .power= fa_icon('power-off')

app/views/admin/users/_device_fields.html.slim
section.device.separated
  = f.hidden_field :id
  aside
    .field
      .radio.drop.right
        - device_icons.each do |sym, str|
          = f.radio_button :icon, str.to_s, {class: 'hidden'}
          = f.label :icon, device_icon(sym), {value: str.to_s}
      label Icon

  main
    .field
      = f.label :name, 'Device Name'
      = f.text_field :name

    .device-lookup-fields
      .field.lookup
        select.select2-device-lookup name="lookup" data-id=f.object&.id
      .row
        .field
          = f.label :host, 'Hostname or IP address'
          = f.text_field :host, {placeholder: 'Enter an IP address manually'}
        .field
          = f.label :mac, 'MAC Address'
          = f.text_field :mac, {placeholder: 'Enter a MAC address manually'}
    .actions
      .active
        = f.check_box :active
        = f.label :active
      - if f.object&.id
        ._destroy
          = f.check_box :_destroy
          = f.label :_destroy do
            span.visible Remove this device
      - else
        .cancel
          = link_to_remove_association('Cancel new device', f, { wrapper_class: 'device' })

app/views/admin/users/_form.html.slim
= form_with(model: [:admin, user], local: true, class: 'user editing', id: user.id) do |form|

  - if user.errors.any?
    section.error_explanation
      h2= pluralize(user.errors.count, "error") + ' prohibited this user from being saved:'

      ul
        - user.errors.full_messages.each do |message|
          li= message
  section.user
    aside
      .field
        label User type
        .radio.drop.right
          = form.radio_button :admin, '1', { :checked => user.admin, :class => 'hidden' }
          = form.label :admin, fa_icon('id-card', text: 'Admin'), { value: '1'}
          = form.radio_button :admin, '0', { :checked => !user.admin, :class => 'hidden' }
          = form.label :admin, fa_icon('user', text: 'User'), { value: '0'}
    main
      .field.name
        = form.label :name
        = form.text_field :name
      .field.email
        = form.label :email
        = form.text_field :email
      .field.password
        = form.label :password
        = form.password_field :password
      .field.password_confirmation
        = form.label :password_confirmation
        = form.password_field :password_confirmation
  .devices
    = form.fields_for :devices, class: 'device' do |devices_form|
      = render 'device_fields', f: devices_form

  .actions
    = link_to_add_association fa_icon('plus', text: 'Add Device'), form, :devices, {class: 'button', data: { association_insertion_node: '.devices', association_insertion_method: :append }}
    - if user.persisted?
      .delete
        = link_to "Delete this user", admin_user_path(user), {method: :delete, data: { confirm: 'Are you sure you want to delete this user?'} }
    = form.submit

app/views/admin/users/_form_device_fields.html.slim
- id = 0
- fname = ->(field) { "user[devices_attributes][#{id}][#{field}]" }
- fid = ->(field) { "user_devices_attributes_#{id}_#{field}]" }

section.device.separated
  input[name=fname('id') id=fid('fid') value=object.id]
  aside
    .field
        .radio.drop.right
          - device_icons.each do |sym, str|
            = input.hidden[type='radio' name=fname('icon') id=fid('icon')+'_'+str value=str
            = devices_form.label :icon, device_icon(sym), {value: sym.to_s}
        label Icon
    .field
      = devices_form.check_box :active
      = devices_form.label :active
    .field._destroy
      = devices_form.check_box :_destroy, class: 'hidden'
      = devices_form.label :_destroy, 'Remove'
  main
    .field
      = devices_form.label :name, 'Device Name'
      = devices_form.text_field :name

    .device-lookup-fields
      .field.lookup
        select.select2-device-lookup name="lookup" data-id=devices_form.object&.id
      hr
      .row
        .field
          = devices_form.label :host, 'Hostname or IP address'
          = devices_form.text_field :host
        .field
          = devices_form.label :mac, 'MAC Address'
          = devices_form.text_field :mac

app/views/admin/users/edit.html.slim
.actions= link_to fa_icon('arrow-left', text: 'Back to all users'), admin_users_path, { class: 'button back' }
= render 'form', user: @user

app/views/admin/users/index.html.slim
h1 Administrators

= render partial: 'card_user', collection: @admins, as: :user

h1 Users

= render partial: 'card_user', collection: @users, as: :user

    / = link_to 'Edit User', edit_admin_user_path(user)
    / = link_to 'Remove User', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }
<br>

.actions= link_to fa_icon("plus", text: "Add a user"), new_admin_user_path, {class: 'button add-user'}

app/views/admin/users/new.html.slim
.actions= link_to fa_icon('arrow-left', text: 'Back to all users'), admin_users_path, { class: 'button back' }
= render 'form', user: @user